# Generated by Django 5.1.2 on 2024-11-14 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], max_length=50)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='dashboard.server')),
            ],
        ),
    ]
