# Generated by Django 5.1.4 on 2024-12-22 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('memory_used_kb', models.IntegerField()),
                ('vcpu_count', models.IntegerField()),
                ('cpu_time_ns', models.BigIntegerField()),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='dashboard.hypervisor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
